name: Run job on another branch

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'
  pull_request:
    types: [ labeled ]

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: git pull && git checkout test/branch
     
    - name: if label exists, echo something
      run: echo ${{ github.event.label.name }}