name: Test job

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: test/branch
    
    - name: Curl github API
      run: |
        curl https://api.github.com/repos/${{github.repository}}/issues/${PR_NUMBER} -u asawo:GITHUB_TOKEN
     
    - name: if label exists, echo something
      run: echo ${{ toJSON(github) }}
      
    env:
      PR_NUMBER: 1
