name: Run job on another branch

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Manually run git checkout
      run: git checkout test/branch
     
    - name: check github object
      run: echo ${{ github }}
