name: Test job

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: test/branch
    
    - name: Manually run git checkout
      run: |
        curl https://api.github.com/repos/asawo/github-actions-playground/labels -u asawo:GITHUB_TOKEN
     
    - name: if label exists, echo something
      run: echo ${{ toJSON(github) }}
