name: Run job on another branch

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        ref: test/branch
     
    - name: if label exists, echo something
      if: ${{ github.event.label.name == 'hello' }}
      run: echo "echo something"