name: Test job

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Manually run git checkout
      run: git branch
     
    - name: if label exists, echo something
      run: echo ${{ toJSON(github) }}
