name: Test job

on:
  workflow_dispatch:
    inputs:
      labelName:
        description: 'label name'
        required: false
        default: 'hello'

jobs:
  testing-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Manually run git checkout
      run: |
        git config --global user.name 'Bot'
        git config --global user.email '<>'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git branch
     
    - name: if label exists, echo something
      run: echo ${{ toJSON(github) }}
